model:
  model_id: dito
  sample_size: [360, 640]
  proxy_sample_size: [45, 80]
  channels: 3
  proxy_channels: 16
  latent_size: 16
  latent_channels: 32

  ch_0: 128
  ch_max: 1024

  encoder_blocks_per_stage: [4, 4, 4, 4, 4]
  decoder_blocks_per_stage: [4, 4, 4, 4, 4]

  use_middle_block: false
  do_channel_mask: false

  n_layers: 28
  n_heads: 24
  d_model: 1536

  patch_size: [1, 2]
  x0_mode: false

train:
  trainer_id: dito
  data_id: video_dir_loader
  data_kwargs:
    source: 
     - /mnt/data/datasets/extracted_tars/kbm/fps/*/*.mp4
     - /mnt/data/datasets/extracted_tars/kbm/3ps/*/*.mp4
     - /mnt/data/datasets/extracted_tars/kbm/other/*/*.mp4
    target_size: [360, 640]

  target_batch_size: 64
  batch_size: 8

  epochs: 200

  opt: Muon
  opt_kwargs:
    lr: 5.0e-4
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-2
    adamw_eps: 1.0e-6
    adamw_betas: [0.9, 0.999]
    adamw_keys:
      - encoder.conv_in
      - encoder.conv_out
      - .down.
      - .residuals.
      - .decoder.proj_in
      - .decoder.proj_out
      - .decoder.ts_embed
      - .decoder.final
      - .adaln1
      - .adaln2
      - .gate1
      - .gate2

  scheduler: null

  checkpoint_dir: checkpoints/waypoint_1_dito_owlc_f32_c32_proxy
  resume_ckpt: null #checkpoints/waypoint_1_vae_owlc_f16_c16/step_200000.pt

  sample_interval: 1000
  save_interval: 5000

  sampling_steps: 50
  use_proxy: true

wandb:
  name: shahbuland
  project: dito
  run_name: waypoint_1_dito_owlc_f32_c32_proxy