model:
  model_id: video_dito
  sample_size: [360, 640]
  channels: 3

  latent_size: 32
  latent_channels: 16

  ch_0: 96
  ch_max: 384

  encoder_blocks_per_stage: [2, 2, 2, 2]
  decoder_blocks_per_stage: [2, 2, 2, 2]

  use_middle_block: false
  do_channel_mask: false

  n_layers: 24
  n_heads: 16
  d_model: 1024

  patch_size: [20, 20]
  x0_mode: true
  temporal_factor: 4
  n_frames: 16
   
  tokens_per_frame: 256
  rope_impl: video

train:
  trainer_id: video_dito
  data_id: video_dir_loader
  data_kwargs:
    source: 
     - /mnt/data/datasets/extracted_tars/kbm/fps/*/*.mp4
     - /mnt/data/datasets/extracted_tars/kbm/3ps/*/*.mp4
     - /mnt/data/datasets/extracted_tars/kbm/other/*/*.mp4
    target_size: [360, 640]
    window_length: 16

  target_batch_size: 64
  batch_size: 2

  epochs: 200

  opt: Muon
  opt_kwargs:
    lr: 5.0e-4
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-2
    adamw_eps: 1.0e-6
    adamw_betas: [0.9, 0.999]
    adamw_keys:
      - encoder.conv_in
      - encoder.conv_out
      - .down.
      - .residuals.
      - .decoder.proj_in
      - .decoder.proj_out
      - .decoder.ts_embed
      - .decoder.final
      - .adaln1
      - .adaln2
      - .gate1
      - .gate2

  scheduler: LinearWarmupWithCosineDecay
  scheduler_kwargs:
    warmup_steps: 1000
    decay_after: 120000
    decay_steps: 220000
    start_mult: 0.1
    decay_to_mult: 0.1

  checkpoint_dir: checkpoints/waypoint_1_video_dito_owlc_f16_c16
  resume_ckpt: null #checkpoints/waypoint_1_vae_owlc_f16_c16/step_200000.pt

  sample_interval: 250
  save_interval: 5000

  sampling_steps: 25
  use_proxy: false

wandb:
  name: shahbuland
  project: video_dito
  run_name: waypoint_1_video_dito_owlc_f16_c16
